import {
  IconHome,
  IconPalette,
  IconComponents,
  IconLayoutDashboard,
  IconColorSwatch,
  IconHandClick,
  IconLayoutCards,
  IconTags,
  IconTable,
  IconForms,
  IconLayoutNavbar,
  IconLayoutNavbarCollapse,
  IconSitemap,
  IconProgressBolt,
  IconLoader,
  IconTextSize,
  IconLayoutColumns,
  IconSlideshow,
  IconInfoCircle,
  IconCloudUpload,
  IconUserCircle,
  IconStairs,
} from '@tabler/icons-react'
import type { NavItem } from './types'

export const NAV_ITEMS: NavItem[] = [
  { key: 'home', labelKey: 'nav.home', path: '/', icon: IconHome },
  { key: 'foundations', labelKey: 'nav.foundations', path: '/foundations', icon: IconPalette },
  {
    key: 'components',
    labelKey: 'nav.components',
    path: '/components',
    icon: IconComponents,
    children: [
      { key: 'button', labelKey: 'nav.comp.button', path: '/components/button', icon: IconHandClick },
      { key: 'card', labelKey: 'nav.comp.card', path: '/components/card', icon: IconLayoutCards },
      { key: 'chips', labelKey: 'nav.comp.chips', path: '/components/chips', icon: IconTags },
      { key: 'data-table', labelKey: 'nav.comp.dataTable', path: '/components/data-table', icon: IconTable },
      { key: 'form', labelKey: 'nav.comp.form', path: '/components/form', icon: IconForms },
      { key: 'header', labelKey: 'nav.comp.header', path: '/components/header', icon: IconLayoutNavbar },
      { key: 'footer', labelKey: 'nav.comp.footer', path: '/components/footer', icon: IconLayoutNavbarCollapse },
      { key: 'navigation', labelKey: 'nav.comp.navigation', path: '/components/navigation', icon: IconSitemap },
      { key: 'progress-bar', labelKey: 'nav.comp.progressBar', path: '/components/progress-bar', icon: IconProgressBolt },
      { key: 'spinner', labelKey: 'nav.comp.spinner', path: '/components/spinner', icon: IconLoader },
      { key: 'rich-text', labelKey: 'nav.comp.richText', path: '/components/rich-text', icon: IconTextSize },
      { key: 'segment-control', labelKey: 'nav.comp.segmentControl', path: '/components/segment-control', icon: IconLayoutColumns },
      { key: 'slider', labelKey: 'nav.comp.slider', path: '/components/slider', icon: IconSlideshow },
      { key: 'tooltip', labelKey: 'nav.comp.tooltip', path: '/components/tooltip', icon: IconInfoCircle },
      { key: 'upload-area', labelKey: 'nav.comp.uploadArea', path: '/components/upload-area', icon: IconCloudUpload },
      { key: 'user-profile', labelKey: 'nav.comp.userProfile', path: '/components/user-profile', icon: IconUserCircle },
      { key: 'wizard', labelKey: 'nav.comp.wizard', path: '/components/wizard', icon: IconStairs },
    ],
  },
  { key: 'layouts', labelKey: 'nav.layouts', path: '/layouts', icon: IconLayoutDashboard },
  { key: 'tokens', labelKey: 'nav.tokens', path: '/tokens', icon: IconColorSwatch },
]
